# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-29 12:01
from __future__ import unicode_literals

import aviatravel_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название категории')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='названия города')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'города',
                'verbose_name_plural': 'город',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='названия страны')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'страны',
                'verbose_name_plural': 'страна',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to=aviatravel_app.models.dir_images, verbose_name='изображеня')),
                ('dir_img', models.CharField(default='84864', max_length=50, verbose_name='название папки')),
            ],
            options={
                'verbose_name': 'изображения',
            },
        ),
        migrations.CreateModel(
            name='TravelTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tick', models.CharField(blank=True, default='84864', max_length=150, null=True, verbose_name='id объекта/папки')),
                ('title', models.CharField(max_length=400, verbose_name='заголовк')),
                ('description', models.TextField(verbose_name='статья')),
                ('target_link', models.URLField()),
                ('date', models.DateTimeField(verbose_name='дата публикации')),
                ('slug', models.SlugField()),
                ('price', models.PositiveIntegerField(default=0, verbose_name='стоимость')),
                ('image', models.ImageField(blank=True, null=True, upload_to=aviatravel_app.models.generate_filename, verbose_name='заглавное изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviatravel_app.Category', verbose_name='категория')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviatravel_app.City', verbose_name='категория')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviatravel_app.Country', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'записи',
                'verbose_name_plural': 'запись',
            },
        ),
        migrations.AddField(
            model_name='images',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviatravel_app.TravelTicket'),
        ),
    ]
